name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    name: centos-stream-8

    env:
      ARTIFACTS_DIR: exported-artifacts

    container:
      image: quay.io/centos/centos:stream8

    steps:
    - name: Prepare CentOS Stream 8 environment
      run: |
        # Install oVirt repositories
        dnf copr enable -y ovirt/ovirt-master-snapshot centos-stream-8
        dnf install -y ovirt-release-master

        # Configure CS8 repositories
        dnf config-manager --enable powertools
        dnf module enable -y pki-deps javapackages-tools

    - name: Install required packages
      run: |
        dnf install -y \
          createrepo_c \
          dnf-utils \
          git \
          gzip \
          java-11-openjdk-devel \
          maven \
          rpm-build \
          sed \
          tar

    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Use cache for maven
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Perform build
      run: |
        .automation/build-rpm.sh $ARTIFACTS_DIR

    - name: Create DNF repository
      run: |
        createrepo_c $ARTIFACTS_DIR

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rpm-cs8
        path: ${{ env.ARTIFACTS_DIR}}
